# Generated by Django 3.2.6 on 2021-09-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='basic_img',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='joint_img',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='outline_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='outline_img',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
