# Generated by Django 3.2.6 on 2021-09-23 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device_pw',
            field=models.CharField(default='0000', max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
